//The Fibonacci Series is a mathematical series that starts with 0 and 1 and is generated by adding the two preceding numbers to generate the next one

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

int main() {int a=0,b=1,c,i,n;
            scanf("%d",&n);
            for(i=1;i<=n;i++)
            {printf("%d ",a);
                c=a+b;
            a=b;
            b=c;
            }
            

    /* Enter your code here. Read input from STDIN. Print output to STDOUT */    
    return 0;
}
